### PR TITLE
Redirect to the correct route when using model binding

### PR DESCRIPTION
**Pull request by markvesterskov**
Redirect to the correct route when using model binding in URLS.

### CODE REVIEW

**Comment by browner12** [comment]
Can you please explain the issue a little more?

What is the difference between `->route()->uri()` and `->fullUrl()`?

If we do switch, should we instead switch to `->fullUrlWithQuery()`?

Please remove the changes to `composer.json`? I will bump the Laravel version myself in another commit.

**Comment by markvesterskov** [comment]
Sorry about the Composer update - i pushed to master because I'm using my branch in a project I'm working on right now.

Check out issue #6 which describes the issue in more detail.

**Comment by browner12** [comment]
interesting, didn't realize it did that.

what are your thoughts on using `->fullUrlWithQuery()`?

**Comment by markvesterskov** [comment]
@browner12 it makes really good sense to go for `->fullUrlWithQuery()` instead, just to cover all use cases. Updated.

**Comment by browner12** [comment]
digging into the source a little more, we cannot call `->fullUrlWithQuery()` without a parameter.  I think what this method is meant for is to *override* the existing query parameters.

Also, `->fullUrl()` actually returns the URL with the full query parameters, so we can switch back to this.

I would *prefer* we find a function that returns a relative path, but have not been able to find one yet. Would you mind looking through the Illuminate and Symfony Request classes to see if you can find one?

If we can't find one, we'll go with `->fullUrl()`.

**Comment by markvesterskov** [comment]
Any reason to prefer a relative path?

**Comment by browner12** [comment]
probably nothing legit, just my personal preference to avoid absolute URLs at all costs because of the problems they've caused me before.

and we are currently returning a relative path, so would prefer to avoid some weirdo edge-case breaking change this might cause.

**Comment by markvesterskov** [comment]
I cant imagine it breaking anything. The redirect URL is saved at runtime by the same app that we redirect back to, so that it is fully qualified shouldn't change anything.

**Pull request merged**
